# Generated by Django 3.1.2 on 2021-03-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210330_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshop',
            name='year',
            field=models.DateTimeField(verbose_name='Год выхоа книги'),
        ),
    ]
