# Generated by Django 3.1.2 on 2021-03-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210330_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshop',
            name='year',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Год выхоа книги'),
        ),
    ]
